on: [push]
 
jobs:   
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@1051d70375d7deb2fe91c815538bec71d0a458a8 #GET Latest Version from https://github.com/marketplace/actions/soos-sast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          api_url: "https://qa-api.soos.io/api/"
          project_name: "GHActions-SAST"
          sast_version: latest
          log_level: DEBUG
          verbose: true
          working_directory: 234
          source_code_path: 23fd
