on: [push]
 
jobs:   
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@e56d507d2216e2de6b85b97e0cff893e4ca8d0ee #GET Latest Version from https://github.com/marketplace/actions/soos-sast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          api_url: https://qa-api.soos.io/api/
          project_name: "GHActions-SAST"
          sast_version: 1.0.10-pre.1
          log_level: DEBUG
          source_code_path: "projectB/sarif-files"
          #export_format: SARIF
          export_file_type: Json
          output_directory: output

      # Cargar el directorio generado como artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: sast-analysis-output
          path: /home/runner/work/gh-actions-SAST/gh-actions-SAST
