on: [push]
 
jobs:   
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/checkout@master
      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@65348f6ff6a3d71239696906796e0c1629293783  #GET Latest Version from https://github.com/marketplace/actions/soos-sast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          api_url: https://qa-api.soos.io/api/
          project_name: "GHActions-SAST"
          sast_version: 1.0.11-pre.1
          log_level: DEBUG
          source_code_path: "projectB/sarif-files"
          export_format: SARIF
          export_file_type: test


      # Cargar el directorio generado como artefacto
      - uses: actions/upload-artifact@v4
        with:
          name: sast-analysis-output
          path: |
              ${{ github.workspace }}/*.cdx.json
              ${{ github.workspace }}/*.cdx.xml
              ${{ github.workspace }}/*.spdx.json
              ${{ github.workspace }}/*.spdx.txt
              ${{ github.workspace }}/*.sarif.json
              ${{ github.workspace }}/*.csafvex.json
              ${{ github.workspace }}/*.sooslicenses.hmtl
              ${{ github.workspace }}/*.sooslicenses.csv
              ${{ github.workspace }}/*.soospackages.hmtl
              ${{ github.workspace }}/*.soospackages.csv
              ${{ github.workspace }}/*.soosvulnerabilities.hmtl
              ${{ github.workspace }}/*.soosvulnerabilities.csv
              ${{ github.workspace }}/*.soosissues.hmtl
              ${{ github.workspace }}/*.soosissues.csv
